---
# tasks file for roles/apache
- name: Instalar Apache2
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Crear página personalizada desde template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: restart apache

- name: Habilitar e iniciar servicio Apache
  service:
    name: apache2
    state: started
    enabled: yes
